ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount DECIMAL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount DECIMAL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount DECIMAL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS financial_currency VARCHAR(3);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS vat_rate INTEGER;
