spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookstore
    username: bookstore
    password: bookstore
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    properties:
      open-in-view: false
      hibernate:
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    outOfOrder: false
    clean-disabled: true
  kafka:
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap-servers: "PLAINTEXT://kafka1:9094"
    # Required connection configs for Confluent Cloud Schema Registry
    properties:
      schema.registry.url: "http://kafka-schema-registry:8081"
      security.protocol: "PLAINTEXT"
      sasl.mechanism: "PLAIN"
logging:
  level:
    org.springframework.data: DEBUG