spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookstore-order
    username: bookstore
    password: bookstore
  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    outOfOrder: false
    clean-disabled: true
    validate-on-migrate: true
  kafka:
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap-servers: "PLAINTEXT://localhost:9094"
    # Required connection configs for Confluent Cloud Schema Registry
    properties:
      schema.registry.url: "http://localhost:8081"
      security.protocol: "PLAINTEXT"
      sasl.mechanism: "PLAIN"

app:
  api:
    cors:
      enabled: true
      allowed-origin-patterns:
        - http://localhost:*
        - http://127.0.0.1:*
      allow-credentials: true
  order:
    vat:
      percentage: 21

logging:
  level:
    org.springframework.data: DEBUG
